import { DISCLAIMER_COPY, FUTURE_SELF_LINES_COPY, GENERATION_LINES_COPY } from "@/lib/content/copyRegistry";

export {
  AI_OUTPUT_POLICY_COPY,
  APP_METADATA_COPY,
  APP_NAV_COPY,
  CANONICAL_TERMS_COPY,
  CONTENT_SYSTEM_OWNER,
  CONTENT_SYSTEM_VERSION,
  DISCLAIMER_COPY,
  DYNAMIC_EVENT_TYPE_COPY,
  FUTURE_SELF_LINES_COPY,
  GENERATION_LINES_COPY,
  LIFE_MAP_DIALOGUE_COPY,
  LIFE_SIMULATION_ROOT_NARRATIVE_COPY,
  LANDING_PAGE_COPY,
  PRODUCT_RESEARCH_BOUNDARY_COPY,
  SHARE_CARD_TEMPLATE_COPY,
  contentRegistry,
  formatContentPolicyForPrompt,
} from "@/lib/content/copyRegistry";

export const generationLines = GENERATION_LINES_COPY.value;
export const proverbs = FUTURE_SELF_LINES_COPY.value;
export const disclaimer = DISCLAIMER_COPY.value;
