import type { ForkContainmentRole, ForkPath, LifeMapRole, LifeScale, LifeStateVector, LifeTimeRange } from "@/lib/types";
import { createLifeMapContentAttribution, rootNarrativeForLane } from "@/lib/content/lifeMapNarratives";
import { buildDynamicTypeBranchSignal } from "@/lib/selfSkill/dynamicTypeRules";
import { MONTH, WEEK, YEAR, containmentRoleForPath, durationMonthsForRange, mapRoleForPath, timeRange } from "@/lib/selfSkill/timeRangeRules";

type TimeModel = {
  mapRole: LifeMapRole;
  scale: LifeScale;
  displayScale?: LifeScale;
  durationMonths?: number;
  containmentRole?: ForkContainmentRole;
  range: LifeTimeRange;
};

const LIFE_RANGE = timeRange(0, 70 * YEAR, "life");
const timeModelById: Record<string, TimeModel> = {
  "life-stability": { mapRole: "life-container", scale: "life", displayScale: "life", durationMonths: 840, containmentRole: "root", range: LIFE_RANGE },
  "stability-3y": { mapRole: "checkpoint", scale: "era", displayScale: "era", durationMonths: 36, containmentRole: "checkpoint", range: timeRange(0, 3 * YEAR, "era") },
  "stability-10y": { mapRole: "checkpoint", scale: "decade", displayScale: "decade", durationMonths: 120, containmentRole: "checkpoint", range: timeRange(0, 10 * YEAR, "decade") },
  "stability-year-1": { mapRole: "period", scale: "year", range: timeRange(0, YEAR, "year") },
  "stability-month-3": { mapRole: "period", scale: "month", range: timeRange(2 * MONTH, 3 * MONTH, "month") },
  "stability-hour-search": { mapRole: "event", scale: "hour", range: timeRange(3 * MONTH - 1 / 24, 3 * MONTH, "hour") },
  "life-leap": { mapRole: "life-container", scale: "life", range: LIFE_RANGE },
  "leap-1y": { mapRole: "period", scale: "year", range: timeRange(0, YEAR, "year") },
  "leap-month-2": { mapRole: "period", scale: "month", range: timeRange(MONTH, 2 * MONTH, "month") },
  "leap-hour-panic": { mapRole: "event", scale: "hour", range: timeRange(2 * MONTH - 1 / 24, 2 * MONTH, "hour") },
  "leap-10y": { mapRole: "checkpoint", scale: "decade", range: timeRange(0, 10 * YEAR, "decade") },
  "life-experiment": { mapRole: "life-container", scale: "life", range: LIFE_RANGE },
  "experiment-90d": { mapRole: "period", scale: "era", range: timeRange(0, 90, "era") },
  "experiment-week-1": { mapRole: "period", scale: "week", range: timeRange(0, WEEK, "week") },
  "experiment-day-output": { mapRole: "event", scale: "day", range: timeRange(3, 4, "day") },
  "experiment-hour-send": { mapRole: "event", scale: "hour", range: timeRange(3 + 21 / 24, 3 + 22 / 24, "hour") },
  "experiment-miss": { mapRole: "event", scale: "week", range: timeRange(2 * WEEK, 3 * WEEK, "week") },
  "experiment-10y": { mapRole: "checkpoint", scale: "decade", range: timeRange(0, 10 * YEAR, "decade") },
  "life-relationship": { mapRole: "life-container", scale: "life", range: LIFE_RANGE },
  "relationship-1y": { mapRole: "period", scale: "year", range: timeRange(0, YEAR, "year") },
  "relationship-day-talk": { mapRole: "event", scale: "day", range: timeRange(120, 121, "day") },
};

function withTimeModel(path: ForkPath): ForkPath {
  const model = timeModelById[path.id];
  const range = model?.range ?? path.timeSpan?.range;
  const durationMonths = model?.durationMonths ?? path.durationMonths ?? path.timeSpan?.durationMonths ?? durationMonthsForRange(range);
  const next: ForkPath = {
    ...path,
    mapRole: model?.mapRole ?? mapRoleForPath(path),
    containmentRole: model?.containmentRole ?? containmentRoleForPath(path),
    scale: model?.scale ?? path.scale,
    displayScale: model?.displayScale ?? path.displayScale ?? model?.scale ?? path.scale,
    durationMonths,
  };

  return {
    ...next,
    timeSpan: next.timeSpan
      ? {
          ...next.timeSpan,
          durationMonths,
          range,
        }
      : next.timeSpan,
  };
}

export function normalizeForkTree(paths: ForkPath[]): ForkPath[] {
  const visit = (path: ForkPath, parentId: string | undefined, depth: number, orderIndex: number): ForkPath => {
    const children = path.children?.map((child, index) => visit(child, path.id, (path.depth ?? depth) + 1, index));
    return withTimeModel({
      ...path,
      parentId,
      depth: path.depth ?? depth,
      orderIndex,
      children,
    });
  };

  return paths.map((path, index) => visit(path, undefined, 1, index));
}

export function buildLifeSimulationMap(currentChoice: string, dynamicTypeEvidenceIds: string[] = []): ForkPath[] {
  const choice = currentChoice || "当前这个选择";
  const consequence = (label: string, delta: Partial<LifeStateVector>) => ({ label, delta });
  const node = ({
    consequences,
    nodeType,
    ...path
  }: ForkPath): ForkPath => {
    const next: ForkPath = {
      nodeType: nodeType ?? "life-map",
      consequences:
        consequences ??
        (path.stateVector
          ? [
              consequence("自主感", { autonomy: path.stateVector.autonomy - 50 }),
              consequence("稳定性", { stability: path.stateVector.stability - 50 }),
              consequence("创造表达", { creation: path.stateVector.creation - 50 }),
              consequence("不确定性", { uncertainty: path.stateVector.uncertainty - 50 }),
            ]
          : undefined),
      ...path,
    };

    return {
      ...next,
      content: next.content ?? createLifeMapContentAttribution(next),
      dynamicType: next.dynamicType ?? buildDynamicTypeBranchSignal(next, dynamicTypeEvidenceIds),
    };
  };
  const stabilityRoot = rootNarrativeForLane("stability");
  const leapRoot = rootNarrativeForLane("leap");
  const experimentRoot = rootNarrativeForLane("experiment");
  const relationshipRoot = rootNarrativeForLane("relationship");

  const roots: ForkPath[] = [
    node({
      id: "life-stability",
      depth: 1,
      scale: "life",
      lane: "stability",
      timeSpan: { startLabel: "现在", endLabel: "晚年", durationLabel: "一整条人生" },
      title: stabilityRoot.title,
      subtitle: stabilityRoot.subtitle,
      summary: stabilityRoot.summary(choice),
      gains: stabilityRoot.gains,
      costs: stabilityRoot.costs,
      futureSelfName: stabilityRoot.futureSelfName,
      futureSelfVoice: stabilityRoot.futureSelfVoice,
      stateVector: { autonomy: 44, stability: 86, intimacy: 58, creation: 35, energy: 52, regret: 64, uncertainty: 24 },
      zoomHint: stabilityRoot.zoomHint,
      children: [
        node({
          id: "stability-3y",
          parentId: "life-stability",
          depth: 2,
          scale: "era",
          lane: "stability",
          timeSpan: { startLabel: "现在", endLabel: "3 年后", durationLabel: "3 年" },
          title: "3 年后：继续维持当前方案",
          subtitle: "生活更稳定，改变的成本也会提高。",
          summary: "三年后，你可能获得更好的职位、关系和资源。当前问题仍未解决，而且工作和生活责任会让调整方向更困难。",
          gains: ["资源积累增加", "收入和生活更稳定", "日常摩擦减少"],
          costs: ["改变成本提高", "个人项目继续推迟", "容易忽略长期不满"],
          futureSelfName: "3 年后稳定线上的你",
          futureSelfVoice: "谨慎、具体，会优先说明现实条件",
          stateVector: { autonomy: 42, stability: 90, intimacy: 61, creation: 32, energy: 49, regret: 68, uncertainty: 20 },
          children: [
            node({
              id: "stability-year-1",
              parentId: "stability-3y",
              depth: 3,
              scale: "year",
              lane: "stability",
              timeSpan: { startLabel: "第 1 年", endLabel: "第 12 个月", durationLabel: "一年" },
              title: "第 1 年：开始记录问题，暂不改变主方案",
              subtitle: "你开始收集信息，但实际行动较少。",
              summary: "这一年里，你会记录问题、与他人讨论并考虑调整方向。现有工作和生活不变，你获得了一些信息，但还没有验证新方案。",
              gains: ["减少冲动决策", "问题描述更清楚", "开始积累判断依据"],
              costs: ["行动频率不足", "容易被日常工作打断", "长期不满可能重复出现"],
              futureSelfName: "第 1 年稳定观察中的你",
              futureSelfVoice: "冷静、具体，重点说明观察结果",
              stateVector: { autonomy: 46, stability: 84, intimacy: 58, creation: 38, energy: 51, regret: 58, uncertainty: 28 },
              children: [
                node({
                  id: "stability-month-3",
                  parentId: "stability-year-1",
                  depth: 4,
                  scale: "month",
                  lane: "stability",
                  timeSpan: { startLabel: "第 3 个月", durationLabel: "一个月" },
                  title: "第 3 个月：记录精力和满意度变化",
                  subtitle: "先收集数据，再判断是否调整方案。",
                  summary: "你开始记录哪些任务消耗最大，哪些活动能提高精力和满意度。这个月的目标是获得足够信息，支持下一步判断。",
                  gains: ["判断更少受情绪影响", "识别主要触发因素", "风险保持较低"],
                  costs: ["变化感弱", "需要持续记录", "容易半途忘记"],
                  futureSelfName: "第 3 个月的观察者",
                  futureSelfVoice: "简洁、客观，会引用记录中的具体变化",
                  stateVector: { autonomy: 48, stability: 82, intimacy: 57, creation: 42, energy: 54, regret: 52, uncertainty: 30 },
                  children: [
                    node({
                      id: "stability-hour-search",
                      parentId: "stability-month-3",
                      depth: 5,
                      scale: "hour",
                      lane: "stability",
                      timeSpan: { startLabel: "23:40", durationLabel: "一小时" },
                      title: "23:40：记录一次反复搜索",
                      subtitle: "这次搜索可以作为兴趣和压力的一个信号。",
                      summary: "你没有执行行动，但记录了自己反复搜索和关注的方向。这可以作为后续判断的一个信号。",
                      gains: ["记录真实关注点", "下一步问题更清楚", "补充方向证据"],
                      costs: ["睡眠被占用", "焦虑可能增加", "仍未产生实际行动"],
                      futureSelfName: "23:40 的你",
                      futureSelfVoice: "犹豫，但能说明自己反复关注的内容",
                      stateVector: { autonomy: 47, stability: 72, intimacy: 47, creation: 50, energy: 28, regret: 70, uncertainty: 42 },
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
        node({
          id: "stability-10y",
          parentId: "life-stability",
          depth: 2,
          scale: "decade",
          lane: "stability",
          timeSpan: { startLabel: "现在", endLabel: "10 年后", durationLabel: "10 年" },
          title: "10 年后：稳定积累带来更多责任",
          subtitle: "资源增加，调整方向也会更困难。",
          summary: "十年后，这条方案可能带来资源、经验和稳定关系。与此同时，你需要考虑收入、家庭和已有投入，调整方向的成本会明显提高。",
          gains: ["资源和信用积累", "关系结构稳固", "生活抗风险能力强"],
          costs: ["转向成本显著上升", "未完成目标继续累积", "个人需求更难对他人说明"],
          futureSelfName: "10 年后稳定线上的你",
          futureSelfVoice: "成熟、谨慎，会同时说明收益和长期代价",
          stateVector: { autonomy: 38, stability: 94, intimacy: 65, creation: 28, energy: 48, regret: 76, uncertainty: 15 },
        }),
      ],
    }),
    node({
      id: "life-leap",
      depth: 1,
      scale: "life",
      lane: "leap",
      timeSpan: { startLabel: "现在", endLabel: "晚年", durationLabel: "一整条人生" },
      title: leapRoot.title,
      subtitle: leapRoot.subtitle,
      summary: leapRoot.summary(choice),
      gains: leapRoot.gains,
      costs: leapRoot.costs,
      futureSelfName: leapRoot.futureSelfName,
      futureSelfVoice: leapRoot.futureSelfVoice,
      stateVector: { autonomy: 84, stability: 34, intimacy: 48, creation: 86, energy: 65, regret: 32, uncertainty: 82 },
      children: [
        node({
          id: "leap-1y",
          parentId: "life-leap",
          depth: 2,
          scale: "year",
          lane: "leap",
          timeSpan: { startLabel: "第 1 年", endLabel: "第 12 个月", durationLabel: "一年" },
          title: "第 1 年：离开原有安排，建立新结构",
          subtitle: "自主性提高，收入和生活稳定性下降。",
          summary: "第一年的主要任务是建立新的工作节奏、收入结构和生活安排。压力、兴奋和疲惫可能同时出现。",
          gains: ["减少旧环境消耗", "开始建立新角色", "获得更多实际反馈"],
          costs: ["现金流压力", "作息和节奏容易散", "关系解释成本高"],
          futureSelfName: "第 1 年转向中的你",
          futureSelfVoice: "语速较快，直接说明新环境中的压力和变化",
          stateVector: { autonomy: 88, stability: 28, intimacy: 44, creation: 82, energy: 58, regret: 28, uncertainty: 88 },
          children: [
            node({
              id: "leap-month-2",
              parentId: "leap-1y",
              depth: 3,
              scale: "month",
              lane: "leap",
              timeSpan: { startLabel: "第 2 个月", durationLabel: "一个月" },
              title: "第 2 个月：开始承担转向后的实际压力",
              subtitle: "旧安排已经结束，新安排还不稳定。",
              summary: "你拥有更多可支配时间，也需要自己安排工作、收入和休息。这个月的重点是建立计划、边界和固定执行节奏。",
              gains: ["了解实际工作方式", "减少不切实际的预期", "开始建立新结构"],
              costs: ["焦虑变具体", "能量波动大", "容易怀疑自己太冲动"],
              futureSelfName: "第 2 个月的你",
              futureSelfVoice: "坦白、直接，会说明自主工作的实际压力",
              stateVector: { autonomy: 90, stability: 25, intimacy: 41, creation: 78, energy: 44, regret: 34, uncertainty: 90 },
              children: [
                node({
                  id: "leap-hour-panic",
                  parentId: "leap-month-2",
                  depth: 4,
                  scale: "hour",
                  lane: "leap",
                  timeSpan: { startLabel: "凌晨 01:20", durationLabel: "一小时" },
                  title: "01:20：现金流压力引发强烈怀疑",
                  subtitle: "这是转向方案中的一次高压时刻。",
                  summary: "你查看账单、未完成内容和未回复消息后，对转向决定产生怀疑。此时需要检查现金储备、工作量和回撤条件，避免在压力峰值做出新决定。",
                  gains: ["恐惧被具体化", "回撤方案变得必要", "你开始学会照顾自己"],
                  costs: ["睡眠受损", "自我怀疑尖锐", "容易做过度补偿决定"],
                  futureSelfName: "01:20 的你",
                  futureSelfVoice: "急促、坦白，会优先说明压力来源",
                  stateVector: { autonomy: 78, stability: 22, intimacy: 37, creation: 74, energy: 20, regret: 40, uncertainty: 94 },
                }),
              ],
            }),
          ],
        }),
        node({
          id: "leap-10y",
          parentId: "life-leap",
          depth: 2,
          scale: "decade",
          lane: "leap",
          timeSpan: { startLabel: "现在", endLabel: "10 年后", durationLabel: "10 年" },
          title: "10 年后：新职业和生活方式基本稳定",
          subtitle: "主要风险从转向失败变为长期维护。",
          summary: "十年后，你可能拥有更完整的作品、技能或新身份。新的问题会变成：如何把创造、身体、关系和长期财务重新放到同一个生活里。",
          gains: ["新身份稳定", "作品/技能复利明显", "自我一致性强"],
          costs: ["需要修复身体和关系消耗", "早期高压可能产生长期影响", "收入和环境仍有不确定性"],
          futureSelfName: "10 年后转向线上的你",
          futureSelfVoice: "稳定、直接，重点说明长期结果和限制",
          stateVector: { autonomy: 86, stability: 58, intimacy: 52, creation: 90, energy: 64, regret: 25, uncertainty: 54 },
          mergeInto: "experiment-10y",
        }),
      ],
    }),
    node({
      id: "life-experiment",
      depth: 1,
      scale: "life",
      lane: "experiment",
      timeSpan: { startLabel: "现在", endLabel: "晚年", durationLabel: "一整条人生" },
      title: experimentRoot.title,
      subtitle: experimentRoot.subtitle,
      summary: experimentRoot.summary(choice),
      gains: experimentRoot.gains,
      costs: experimentRoot.costs,
      futureSelfName: experimentRoot.futureSelfName,
      futureSelfVoice: experimentRoot.futureSelfVoice,
      stateVector: { autonomy: 70, stability: 62, intimacy: 56, creation: 72, energy: 66, regret: 30, uncertainty: 56 },
      children: [
        node({
          id: "experiment-90d",
          parentId: "life-experiment",
          depth: 2,
          scale: "era",
          lane: "experiment",
          timeSpan: { startLabel: "今天", endLabel: "90 天后", durationLabel: "90 天" },
          title: "90 天：用一次试验验证新方向",
          subtitle: "保留现有生活，用三个月收集实际结果。",
          summary: "90 天内，你只验证一件事：这个方向能否持续产出内容、提高精力、获得他人反馈或带来收入。试验可以停止或调整，整体风险可控。",
          gains: ["信息质量提升", "行动成本可控", "自我信任开始累积"],
          costs: ["需要持续执行", "会面对外部反馈", "需要接受方向可能不适合"],
          futureSelfName: "90 天实验后的你",
          futureSelfVoice: "清醒、具体，会引用三个月的实际结果",
          stateVector: { autonomy: 74, stability: 58, intimacy: 55, creation: 76, energy: 64, regret: 28, uncertainty: 58 },
          children: [
            node({
              id: "experiment-week-1",
              parentId: "experiment-90d",
              depth: 3,
              scale: "week",
              lane: "experiment",
              timeSpan: { startLabel: "第 1 周", durationLabel: "一周" },
              title: "第 1 周：完成一个最小测试",
              subtitle: "先做出可检查的结果，再判断方向。",
              summary: "这一周只完成一项任务，例如一页草稿、一次咨询、一封邮件、一个 Demo 或一次公开发布。完成后根据实际反馈决定是否继续。",
              gains: ["启动阻力低", "反馈开始出现", "更容易复盘"],
              costs: ["结果可能很粗糙", "可能因为要求过高而拖延", "需要接受初版不完善"],
              futureSelfName: "第 1 周开始试验的你",
              futureSelfVoice: "具体、略显紧张，会说明首次测试结果",
              stateVector: { autonomy: 72, stability: 57, intimacy: 54, creation: 74, energy: 60, regret: 27, uncertainty: 60 },
              children: [
                node({
                  id: "experiment-day-output",
                  parentId: "experiment-week-1",
                  depth: 4,
                  scale: "day",
                  lane: "experiment",
                  timeSpan: { startLabel: "第 4 天", durationLabel: "一天" },
                  title: "第 4 天：完成第一个可展示结果",
                  subtitle: "质量还不稳定，但已经可以获得外部反馈。",
                  summary: "这一天，你完成并展示了一个小结果。它的作用是获得实际反馈，帮助你判断新方向是否值得继续。",
                  gains: ["获得实际证据", "执行信心上升", "下一步更具体"],
                  costs: ["初版可能不满意", "反馈不可控", "需要根据结果继续调整"],
                  futureSelfName: "交出第一个产物的你",
                  futureSelfVoice: "紧张但具体，会说明完成后的真实反应",
                  stateVector: { autonomy: 76, stability: 55, intimacy: 53, creation: 82, energy: 68, regret: 22, uncertainty: 62 },
                  children: [
                    node({
                      id: "experiment-hour-send",
                      parentId: "experiment-day-output",
                      depth: 5,
                      scale: "hour",
                      lane: "experiment",
                      timeSpan: { startLabel: "21:10", durationLabel: "一小时" },
                      title: "21:10：你按下发送",
                      subtitle: "发送后，你会获得第一批外部反馈。",
                      summary: "你修改内容后按下发送。这次行动不会立即改变整体生活，但会产生可以记录和分析的反馈。",
                      gains: ["现实反馈开始", "自我信任增加", "恐惧从抽象变具体"],
                      costs: ["等待反馈会增加焦虑", "需要接受他人评价", "可能产生撤回冲动"],
                      futureSelfName: "21:10 的你",
                      futureSelfVoice: "短句、直接，重点说明首次执行结果",
                      stateVector: { autonomy: 80, stability: 51, intimacy: 52, creation: 86, energy: 62, regret: 20, uncertainty: 68 },
                    }),
                  ],
                }),
              ],
            }),
            node({
              id: "experiment-miss",
              parentId: "experiment-90d",
              depth: 3,
              scale: "week",
              lane: "experiment",
              timeSpan: { startLabel: "第 3 周", durationLabel: "一周" },
              title: "第 3 周：你第一次失约",
              subtitle: "先分析失约原因，再调整任务。",
              summary: "你错过了计划时间。这可能说明任务过大、时间安排不合理，或者你担心收到负面反馈。",
              gains: ["识别主要阻力", "可以重新设计任务", "区分时间不足和逃避"],
              costs: ["自责上升", "节奏中断", "容易放弃整个实验"],
              futureSelfName: "第 3 周失约后的你",
              futureSelfVoice: "低沉、诚实，会具体说明未完成原因",
              stateVector: { autonomy: 60, stability: 55, intimacy: 52, creation: 62, energy: 42, regret: 38, uncertainty: 62 },
            }),
          ],
        }),
        node({
          id: "experiment-10y",
          parentId: "life-experiment",
          depth: 2,
          scale: "decade",
          lane: "experiment",
          timeSpan: { startLabel: "现在", endLabel: "10 年后", durationLabel: "10 年" },
          title: "10 年后：形成持续测试和调整的决策方式",
          subtitle: "长期方向通过多次小规模测试逐步确定。",
          summary: "十年后，你形成了持续测试、记录结果和调整计划的习惯。它降低单次决策风险，也需要长期执行。",
          gains: ["自主与稳定更平衡", "长期后悔风险降低", "对自己的判断更有信心"],
          costs: ["决策速度较慢", "需要持续记录和复盘", "可能错过部分高风险机会"],
          futureSelfName: "10 年后实验线上的你",
          futureSelfVoice: "稳定、具体，重点说明测试结果和调整过程",
          stateVector: { autonomy: 78, stability: 72, intimacy: 62, creation: 82, energy: 72, regret: 20, uncertainty: 36 },
        }),
      ],
    }),
    node({
      id: "life-relationship",
      depth: 1,
      scale: "life",
      lane: "relationship",
      timeSpan: { startLabel: "现在", endLabel: "晚年", durationLabel: "一整条人生" },
      title: relationshipRoot.title,
      subtitle: relationshipRoot.subtitle,
      summary: relationshipRoot.summary(choice),
      gains: relationshipRoot.gains,
      costs: relationshipRoot.costs,
      futureSelfName: relationshipRoot.futureSelfName,
      futureSelfVoice: relationshipRoot.futureSelfVoice,
      stateVector: { autonomy: 62, stability: 64, intimacy: 82, creation: 58, energy: 60, regret: 36, uncertainty: 50 },
      children: [
        node({
          id: "relationship-1y",
          parentId: "life-relationship",
          depth: 2,
          scale: "year",
          lane: "relationship",
          timeSpan: { startLabel: "第 1 年", durationLabel: "一年" },
          title: "第 1 年：你开始和重要的人讨论计划",
          subtitle: "让相关人员了解计划、风险和支持需求。",
          summary: "这一年里，你会说明目标、风险和需要的支持。通过对方的反馈，可以判断哪些关系适合参与这个计划。",
          gains: ["支持者出现", "边界感增强", "选择变得更现实"],
          costs: ["可能被误读", "关系会经历压力测试", "你要承受内疚感"],
          futureSelfName: "第 1 年谈判关系的你",
          futureSelfVoice: "略显紧张，但表达更明确",
          stateVector: { autonomy: 66, stability: 62, intimacy: 78, creation: 60, energy: 58, regret: 32, uncertainty: 52 },
          children: [
            node({
              id: "relationship-day-talk",
              parentId: "relationship-1y",
              depth: 3,
              scale: "day",
              lane: "relationship",
              timeSpan: { startLabel: "一次重要谈话", durationLabel: "一天" },
              title: "一次重要谈话：完整说明你的计划",
              subtitle: "你说明了目标、顾虑和需要的支持。",
              summary: "这一天，你把计划、风险和现实条件一起说明。对方的反馈会影响方案，但最终决定仍由你负责。",
              gains: ["减少信息不对称", "检查自己的表达", "支持条件和边界更清楚"],
              costs: ["可能失望", "可能激化旧矛盾", "会暴露不确定"],
              futureSelfName: "那次谈话后的你",
              futureSelfVoice: "紧张、诚实，会清楚说明计划和顾虑",
              stateVector: { autonomy: 70, stability: 58, intimacy: 80, creation: 62, energy: 52, regret: 26, uncertainty: 56 },
            }),
          ],
        }),
      ],
    }),
  ];

  return normalizeForkTree(roots);
}

export function buildLifeForks(currentChoice: string): ForkPath[] {
  const choice = currentChoice || "当前这个选择";
  const node = (path: ForkPath): ForkPath => {
    const next: ForkPath = { nodeType: "life-node", ...path };
    return {
      ...next,
      content: next.content ?? createLifeMapContentAttribution(next),
    };
  };

  const roots: ForkPath[] = [
    node({
      id: "node-still-tonight",
      depth: 1,
      title: "第 1 个夜晚：暂不行动",
      subtitle: "先休息一晚，第二天再判断。",
      summary: `针对「${choice}」，你今晚不做决定。明天重新检查情绪强度和现实条件，确认这是一时冲动还是持续问题。`,
      gains: ["避免在情绪峰值行动", "获得短暂缓冲", "可以检查想法是否持续"],
      costs: ["核心问题可能继续推迟", "容易把暂缓当成解决", "缺少新的判断依据"],
      futureSelfName: "明天早上的你",
      futureSelfVoice: "简短、谨慎，会先检查情绪和事实",
      children: [
        node({
          id: "node-still-note",
          parentId: "node-still-tonight",
          depth: 2,
          title: "第 2 天：记录问题和触发条件",
          subtitle: "先形成记录，再判断是否行动。",
          summary: "你记录什么时候最想改变、什么时候又需要稳定。这些内容可以帮助你识别触发条件，减少单纯依赖情绪做判断。",
          gains: ["问题更清楚", "开始识别触发条件", "减少情绪化判断"],
          costs: ["会看到之前忽略的问题", "需要诚实记录", "短期焦虑可能增加"],
          futureSelfName: "写下第一页后的你",
          futureSelfVoice: "克制、客观，会引用刚刚记录的内容",
          children: [
            node({
              id: "node-still-note-talk",
              parentId: "node-still-note",
              depth: 3,
              title: "第 1 次讨论：向可信的人说明问题",
              subtitle: "通过外部反馈检查你的判断。",
              summary: "你向一个可信的人说明问题，并请对方复述和提问。这样可以检查你的表达是否清楚，也能获得一个外部视角。",
              gains: ["获得外部反馈", "表达会更清楚", "减少独自判断的压力"],
              costs: ["可能被误解", "需要说明个人目标", "问题会变得更具体"],
              futureSelfName: "说出口后的你",
              futureSelfVoice: "略显紧张，但表达比之前更清楚",
              children: [
                node({
                  id: "node-still-note-talk-seen",
                  parentId: "node-still-note-talk",
                  depth: 4,
                  title: "第 1 次有效反馈：对方帮助你拆解问题",
                  subtitle: "对方没有替你决定，只帮你补充信息。",
                  summary: "对方没有直接给结论。他帮助你确认：你需要解决的可能是能力长期没有被使用。你可以据此设计一个小测试。",
                  gains: ["自我理解变清楚", "不再只有 A/B", "情绪压力下降"],
                  costs: ["需要面对长期问题", "需要安排下一步行动", "双方需要继续沟通"],
                  futureSelfName: "获得有效反馈后的你",
                  futureSelfVoice: "松一点，但仍然谨慎",
                  children: [
                    node({
                      id: "node-still-note-talk-seen-small",
                      parentId: "node-still-note-talk-seen",
                      depth: 5,
                      title: "第 1 个小任务：安排两小时执行",
                      subtitle: "先把计划放进日历。",
                      summary: "你在日历里安排两个小时，用于完成与新方向相关的任务。这项安排风险低，也能提供第一份执行记录。",
                      gains: ["行动风险低", "目标获得执行时间", "可以积累完成记录"],
                      costs: ["看起来太小", "容易被临时事务挤掉", "需要守住边界"],
                      futureSelfName: "守住两小时后的你",
                      futureSelfVoice: "轻松一些，会说明两小时内完成了什么",
                      children: [
                        node({
                          id: "node-still-note-talk-seen-small-repeat",
                          parentId: "node-still-note-talk-seen-small",
                          depth: 6,
                          title: "第 4 周：任务开始形成固定节奏",
                          subtitle: "持续执行比短期兴奋更有参考价值。",
                          summary: "你没有每次都按计划完成，但会继续回来执行。这说明目标已经从想法变成可重复的日常任务。",
                          gains: ["方向可信度上升", "行动开始稳定", "不再只靠情绪高峰"],
                          costs: ["节奏慢", "需要长期维护", "仍然没有最终答案"],
                          futureSelfName: "四周后还在继续的你",
                          futureSelfVoice: "平静、具体，会说明四周完成率和主要阻力",
                        }),
                      ],
                    }),
                  ],
                }),
                node({
                  id: "node-still-note-talk-misread",
                  parentId: "node-still-note-talk",
                  depth: 4,
                  title: "第 1 次无效反馈：对方误解了你的问题",
                  subtitle: "这次反馈无法直接支持你的判断。",
                  summary: "对方把问题简单归结为不稳定、想太多或不现实。你需要判断是表达不清，还是对方缺少相关经验，并选择更合适的讨论对象。",
                  gains: ["筛选出不适合的听众", "边界意识变强", "看见自己为何沉默"],
                  costs: ["表达意愿下降", "更倾向独自处理", "可能怀疑自己的判断"],
                  futureSelfName: "收到无效反馈后的你",
                  futureSelfVoice: "防御、谨慎，会重新检查表达和讨论对象",
                }),
              ],
            }),
            node({
              id: "node-still-note-hide",
              parentId: "node-still-note",
              depth: 3,
              title: "第 1 次中断记录：删除刚写下的内容",
              subtitle: "记录被删除，问题仍未处理。",
              summary: "你写下内容后因为不适而删除或关闭。短期压力下降，但之后会缺少用于判断问题持续时间和强度的记录。",
              gains: ["短期轻松一点", "不用立刻面对", "外表秩序不变"],
              costs: ["记录丢失", "下一次更难讨论", "长期不满可能再次出现"],
              futureSelfName: "删掉记录后的你",
              futureSelfVoice: "简短、回避，无法提供足够判断依据",
            }),
          ],
        }),
        node({
          id: "node-still-numb",
          parentId: "node-still-tonight",
          depth: 2,
          title: "第 7 天：问题暂时被日常事务覆盖",
          subtitle: "情绪强度下降，核心问题仍未解决。",
          summary: "你不再强烈纠结，因为日常任务重新占据注意力。短期更轻松，但长期疲惫和不满可能继续累积。",
          gains: ["短期稳定", "不用解释", "冲突降低"],
          costs: ["行动意愿下降", "继续推迟处理", "对问题的记录不足"],
          futureSelfName: "一周后暂缓处理的你",
          futureSelfVoice: "安静、合理化，会强调暂时维持现状的理由",
        }),
      ],
    }),
    node({
      id: "node-leave-first",
      depth: 1,
      title: "第 1 个决定：你开始认真准备离开",
      subtitle: "把转向所需的条件逐项列清楚。",
      summary: `你把「${choice}」从情绪变成计划：钱、时间、作品、关系沟通和失败回撤都被摊开。`,
      gains: ["自我一致性增强", "问题变成计划", "现实开始被纳入"],
      costs: ["压力上升", "需要面对资源限制", "会触发关系里的担心"],
      futureSelfName: "开始准备离开的你",
      futureSelfVoice: "直接、清醒，会逐项说明资源和风险",
      children: [
        node({
          id: "node-leave-money",
          parentId: "node-leave-first",
          depth: 2,
          title: "第 1 张表：计算资金和最低成本",
          subtitle: "用数字检查转向条件。",
          summary: "你计算现金可以维持几个月、每月最低成本和失败后的回撤方案。这些数字可以判断是否需要先增加储备。",
          gains: ["预期更接近现实", "风险更清楚", "可以判断是否需要缓冲"],
          costs: ["焦虑可能增加", "可能因资源不足暂停", "需要调整原计划"],
          futureSelfName: "看完数字后的你",
          futureSelfVoice: "务实、紧张，会引用预算和时间数据",
          children: [
            node({
              id: "node-leave-money-buffer",
              parentId: "node-leave-money",
              depth: 3,
              title: "第 2 个决定：你给离开加缓冲",
              subtitle: "先增加储备，再执行转向。",
              summary: "你决定先攒出现金流、作品雏形或客户线索，再真正离开。改变被延后，但没有被取消。",
              gains: ["风险下降", "成功概率上升", "基本生活更有保障"],
              costs: ["需要忍受过渡期", "容易拖太久", "别人可能看不见你在变"],
              futureSelfName: "带缓冲的你",
              futureSelfVoice: "稳健、直接，会强调转向前置条件",
              children: [
                node({
                  id: "node-leave-money-buffer-launch",
                  parentId: "node-leave-money-buffer",
                  depth: 4,
                  title: "第 1 次公开：发布第一个作品或申请",
                  subtitle: "开始收集外部反馈。",
                  summary: "你发布了第一份作品或申请。反馈可能有限，但可以帮助你判断方向、内容和目标受众。",
                  gains: ["获得实际反馈", "新角色更明确", "下一步更具体"],
                  costs: ["害怕被评价", "结果波动影响心情", "需要持续产出"],
                  futureSelfName: "第一次公开后的你",
                  futureSelfVoice: "紧张但具体，会说明收到的反馈",
                  children: [
                    node({
                      id: "node-leave-money-buffer-launch-continue",
                      parentId: "node-leave-money-buffer-launch",
                      depth: 5,
                      title: "第 2 次反馈：收到明确的正向结果",
                      subtitle: "这条反馈支持继续测试，但还不能证明长期可行。",
                      summary: "某个用户、数据或对话给出正向反馈。你可以记录反馈来源，并设计下一次测试，避免用单次结果替代长期判断。",
                      gains: ["执行信心上升", "方向有了初步证据", "更愿意主动行动"],
                      costs: ["预期可能过快上升", "需要继续验证", "需要更系统的计划"],
                      futureSelfName: "收到正向反馈后的你",
                      futureSelfVoice: "积极但谨慎，会区分单次反馈和长期结果",
                    }),
                  ],
                }),
                node({
                  id: "node-leave-money-buffer-endless",
                  parentId: "node-leave-money-buffer",
                  depth: 4,
                  title: "第 3 个月：准备工作持续，但没有发布",
                  subtitle: "准备时间过长，缺少实际验证。",
                  summary: "你完成了许多准备，却没有发布、申请或谈判。需要设置明确截止日期，避免准备阶段无限延长。",
                  gains: ["能力累积", "资源更多", "风险暂时低"],
                  costs: ["没有实际反馈", "行动意愿下降", "自我怀疑增加"],
                  futureSelfName: "准备太久的你",
                  futureSelfVoice: "克制、疲惫，会指出准备和行动之间的差距",
                }),
              ],
            }),
            node({
              id: "node-leave-money-leap",
              parentId: "node-leave-money",
              depth: 3,
              title: "第 2 个决定：在储备不足时直接转向",
              subtitle: "接受较高风险，立即结束原有安排。",
              summary: "你了解资金和时间风险后仍然决定离开。接下来必须尽快建立收入、工作节奏和回撤方案。",
              gains: ["自我一致性极强", "旧消耗停止", "反馈速度加快"],
              costs: ["现金流压力陡升", "孤独感增加", "容易燃烧过度"],
              futureSelfName: "跳出去后的你",
              futureSelfVoice: "急促、直接，会优先说明短期压力",
              children: [
                node({
                  id: "node-leave-money-leap-chaos",
                  parentId: "node-leave-money-leap",
                  depth: 4,
                  title: "第 14 天：工作和生活节奏失去结构",
                  subtitle: "原有安排结束，新计划尚未建立。",
                  summary: "你拥有更多时间，也失去外部提供的工作结构。现在需要建立固定起止时间、每周目标和休息安排。",
                  gains: ["识别实际需求", "开始建立执行系统", "预期更接近现实"],
                  costs: ["压力高", "作息崩坏风险", "容易怀疑选择"],
                  futureSelfName: "第 14 天调整节奏的你",
                  futureSelfVoice: "坦白、直接，会说明作息和执行问题",
                }),
              ],
            }),
          ],
        }),
        node({
          id: "node-leave-talk",
          parentId: "node-leave-first",
          depth: 2,
          title: "第 1 次谈判：你向重要的人解释",
          subtitle: "说明转向对共同生活和关系的影响。",
          summary: "你向重要的人说明转向原因、风险和需要的支持。对方的反馈可以帮助你检查方案对共同生活的实际影响。",
          gains: ["沟通更透明", "可能获得支持", "练习清楚表达目标"],
          costs: ["可能被反对", "会感到内疚", "解释成本很高"],
          futureSelfName: "解释之后的你",
          futureSelfVoice: "紧张、诚实，会说明关系影响和边界",
        }),
      ],
    }),
    node({
      id: "node-test-first",
      depth: 1,
      title: "第 1 个小实验：先做一次低风险测试",
      subtitle: "暂不做最终决定，先收集结果。",
      summary: `你暂时不对「${choice}」做最终决定，只设计一个成本可控、能在现实中获得反馈的任务。`,
      gains: ["整体风险降低", "目标开始执行", "能获得实际信息"],
      costs: ["需要自律", "会面对反馈", "可能发现自己没那么想要"],
      futureSelfName: "90 天后的你",
      futureSelfVoice: "清醒、具体，会根据测试结果给出下一步",
      children: [
        node({
          id: "node-test-calendar",
          parentId: "node-test-first",
          depth: 2,
          title: "第 1 次排期：设置日期、时长和交付物",
          subtitle: "把测试变成可执行任务。",
          summary: "你为测试设置具体日期、时长和交付物。完成后可以根据结果复盘，不再停留在想法阶段。",
          gains: ["开始变得可执行", "逃避空间变小", "更容易复盘"],
          costs: ["可能占用休息时间", "需要按时执行", "会暴露实际执行能力"],
          futureSelfName: "排好日历后的你",
          futureSelfVoice: "具体、平静，会说明排期和交付标准",
          children: [
            node({
              id: "node-test-first-output",
              parentId: "node-test-calendar",
              depth: 3,
              title: "第 1 个交付物：完成可检查的初版",
              subtitle: "现在可以根据结果判断。",
              summary: "你完成了一个小作品、申请、草稿或谈话记录。初版质量有限，但已经可以用于检查兴趣、能力和外部反馈。",
              gains: ["获得实际证据", "执行信心上升", "下一步更清楚"],
              costs: ["初版可能不满意", "需要继续迭代", "反馈不可控"],
              futureSelfName: "交付第一个产物的你",
              futureSelfVoice: "紧张但具体，会说明交付结果",
              children: [
                node({
                  id: "node-test-first-output-good",
                  parentId: "node-test-first-output",
                  depth: 4,
                  title: "第 1 个正向反馈：有人回应",
                  subtitle: "记录反馈，继续验证。",
                  summary: "有人认可、追问或使用了你的结果。这是支持继续测试的信号，但仍需要更多样本。",
                  gains: ["方向更清楚", "获得继续测试的依据", "低风险方案开始成形"],
                  costs: ["期待上升", "需要承担更多", "害怕失去这个信号"],
                  futureSelfName: "收到正向反馈后的你",
                  futureSelfVoice: "积极、谨慎，会提醒你继续收集样本",
                  children: [
                    node({
                      id: "node-test-first-output-good-next",
                      parentId: "node-test-first-output-good",
                      depth: 5,
                      title: "第 2 个实验：你开始重复它",
                      subtitle: "用重复测试判断结果能否稳定出现。",
                      summary: "你没有用第一次反馈直接下结论，接着设计了第二次、第三次测试。重复结果可以提高判断的可靠性。",
                      gains: ["路线逐渐稳定", "能力开始复利", "选择不再只靠焦虑驱动"],
                      costs: ["新增执行责任", "需要建立流程", "需要接受结果可能不稳定"],
                      futureSelfName: "开始重复测试的你",
                      futureSelfVoice: "稳定、具体，会比较多次测试结果",
                      children: [
                        node({
                          id: "node-test-first-output-good-next-identity",
                          parentId: "node-test-first-output-good-next",
                          depth: 6,
                          title: "第 90 天：新方向进入你的正式计划",
                          subtitle: "连续执行让新角色有了事实依据。",
                          summary: "经过 90 天测试，你已经积累交付物、反馈和执行记录。现在可以决定继续兼顾、扩大投入或停止。",
                          gains: ["新角色有了依据", "原问题更清楚", "可选方案增加"],
                          costs: ["仍需继续选择", "需要向他人解释", "必须根据证据调整预期"],
                          futureSelfName: "完成 90 天测试后的你",
                          futureSelfVoice: "具体、坚定，会根据记录给出判断",
                        }),
                      ],
                    }),
                  ],
                }),
                node({
                  id: "node-test-first-output-silent",
                  parentId: "node-test-first-output",
                  depth: 4,
                  title: "第 1 次无反馈：结果没有获得回应",
                  subtitle: "检查渠道、内容和评估指标。",
                  summary: "你完成了交付物，但没有获得预期反馈。需要判断原因来自内容、发布渠道、样本量，还是你更重视完成本身。",
                  gains: ["动机被校准", "减少幻想", "下一次实验更准"],
                  costs: ["自尊波动", "会想退回去", "需要重设指标"],
                  futureSelfName: "收到无反馈结果后的你",
                  futureSelfVoice: "缓慢、准确，会区分内容问题和渠道问题",
                }),
              ],
            }),
            node({
              id: "node-test-calendar-miss",
              parentId: "node-test-calendar",
              depth: 3,
              title: "第 1 次失约：你没有去做",
              subtitle: "未完成也能提供任务设计信息。",
              summary: "你错过了自己定下的时间。它也在提示你：阻力可能来自害怕真实反馈。",
              gains: ["识别主要阻力", "可以缩小任务", "区分时间不足和逃避"],
              costs: ["自责", "节奏中断", "容易放弃整个实验"],
              futureSelfName: "第一次失约后的你",
              futureSelfVoice: "低沉、诚实，会说明未完成原因",
              children: [
                node({
                  id: "node-test-calendar-miss-smaller",
                  parentId: "node-test-calendar-miss",
                  depth: 4,
                  title: "第 2 次设计：你把动作再缩小",
                  subtitle: "降低启动成本，保留测试目标。",
                  summary: "你把两小时改成二十分钟，把完整作品改成一页草稿。任务更容易开始，也更适合检查真实阻力。",
                  gains: ["重新启动", "减少自责", "更懂自己的阻力"],
                  costs: ["单次产出较少", "进度更慢", "需要接受小步推进"],
                  futureSelfName: "重新启动的你",
                  futureSelfVoice: "务实、具体，会优先降低任务启动成本",
                }),
              ],
            }),
          ],
        }),
        node({
          id: "node-test-message",
          parentId: "node-test-first",
          depth: 2,
          title: "第 1 条消息：你约了一个懂这件事的人",
          subtitle: "通过专业交流补充信息。",
          summary: "你联系一位同行、朋友或前辈，讨论这个方案。对话可以补充行业、技能和执行条件方面的信息。",
          gains: ["获得外部视角", "减少信息盲区", "更快确定下一步"],
          costs: ["会暴露不确定", "可能被敷衍", "需要承受外界节奏"],
          futureSelfName: "发出消息后的你",
          futureSelfVoice: "略显紧张，但能清楚说明想了解的问题",
          children: [
            node({
              id: "node-test-message-meet",
              parentId: "node-test-message",
              depth: 3,
              title: "第 1 次见面：补充了新的方案条件",
              subtitle: "对话增加了行业、技能和时间信息。",
              summary: "对话让你看见自己之前一直把问题想成 A/B，但现实里还有行业、技能、节奏、关系和身份的组合方式。",
              gains: ["选择空间扩大", "信息质量上升", "焦虑更具体"],
              costs: ["复杂度上升", "不能再靠单一答案", "需要整理信息"],
              futureSelfName: "对话之后的你",
              futureSelfVoice: "清醒、兴奋，会列出新获得的信息和待确认项",
            }),
          ],
        }),
      ],
    }),
  ];

  return normalizeForkTree(roots);
}

export function buildSimpleForks(currentChoice: string): ForkPath[] {
  return buildLifeForks(currentChoice);
}
